steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/nix-remote-build/nix-remote-builder:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/nix-remote-build/nix-remote-builder:latest']
images:
- 'gcr.io/nix-remote-build/nix-remote-builder:latest'

